//
//  ClipboardManager.swift
//  boringNotch
//
//  Keeps a local, searchable history of everything copied to the pasteboard.
//

import AppKit
import Combine
import Defaults

struct ClipboardItem: Identifiable, Codable, Equatable {
    enum Kind: String, Codable, CaseIterable {
        case text
        case link
        case image
        case file
    }

    let id: UUID
    let kind: Kind
    /// Plain text for `.text`, the absolute URL string for `.link`.
    var text: String?
    /// File paths for `.file`.
    var filePaths: [String]?
    /// PNG data for `.image`. Images are kept in memory only and are not written to disk.
    var imageData: Data?
    let date: Date
    let sourceBundleID: String?

    enum CodingKeys: String, CodingKey {
        case id, kind, text, filePaths, date, sourceBundleID
    }

    var searchableText: String {
        switch kind {
        case .text, .link:
            return text ?? ""
        case .file:
            return (filePaths ?? []).map { ($0 as NSString).lastPathComponent }.joined(separator: " ")
        case .image:
            return "image"
        }
    }

    /// Two clips hold the same content, regardless of when or where they were copied.
    func hasSameContent(as other: ClipboardItem) -> Bool {
        kind == other.kind && text == other.text && filePaths == other.filePaths && imageData == other.imageData
    }
}

@MainActor
final class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()

    @Published private(set) var items: [ClipboardItem] = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var pollTimer: Timer?
    private var cancellables: Set<AnyCancellable> = []
    private let fileURL: URL
    private let encoder = JSONEncoder()
    private let decoder = JSONDecoder()

    /// Types that apps mark as private or short-lived (see nspasteboard.org).
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    private let passwordManagerBundleIDs: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.dashlane.dashlanephonefinal",
        "in.sinew.Enpass-Desktop",
        "com.lastpass.LastPass",
        "org.keepassxc.keepassxc",
    ]

    /// Long text is trimmed before it is stored so the history stays small.
    private let maxStoredTextLength = 20_000

    private init() {
        lastChangeCount = pasteboard.changeCount

        let fm = FileManager.default
        let support = try? fm.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
        let dir = (support ?? fm.temporaryDirectory).appendingPathComponent("boringNotch", isDirectory: true).appendingPathComponent("Clipboard", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        fileURL = dir.appendingPathComponent("history.json")
        encoder.dateEncodingStrategy = .iso8601
        decoder.dateDecodingStrategy = .iso8601

        load()

        Defaults.publisher(.showClipboardTab)
            .sink { [weak self] change in
                Task { @MainActor in
                    if change.newValue {
                        self?.startMonitoring()
                    } else {
                        self?.stopMonitoring()
                    }
                }
            }
            .store(in: &cancellables)

        Defaults.publisher(.clipboardHistoryLimit)
            .sink { [weak self] _ in
                Task { @MainActor in self?.trimToLimit() }
            }
            .store(in: &cancellables)
    }

    // MARK: Monitoring

    func startMonitoring() {
        guard pollTimer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.checkPasteboard() }
        }
        RunLoop.main.add(timer, forMode: .common)
        pollTimer = timer
    }

    func stopMonitoring() {
        pollTimer?.invalidate()
        pollTimer = nil
    }

    private func checkPasteboard() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: ignoredTypes) else { return }

        let sourceBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if Defaults[.clipboardIgnorePasswordManagers],
           let sourceBundleID, passwordManagerBundleIDs.contains(sourceBundleID) {
            return
        }

        guard let item = readCurrentItem(sourceBundleID: sourceBundleID) else { return }
        insert(item)
    }

    private func readCurrentItem(sourceBundleID: String?) -> ClipboardItem? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipboardItem(id: UUID(), kind: .file, filePaths: urls.map(\.path), date: Date(), sourceBundleID: sourceBundleID)
        }

        if let string = pasteboard.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            if let url = URL(string: trimmed), let scheme = url.scheme?.lowercased(),
               ["http", "https"].contains(scheme), !trimmed.contains(where: \.isWhitespace) {
                return ClipboardItem(id: UUID(), kind: .link, text: trimmed, date: Date(), sourceBundleID: sourceBundleID)
            }
            return ClipboardItem(id: UUID(), kind: .text, text: String(string.prefix(maxStoredTextLength)), date: Date(), sourceBundleID: sourceBundleID)
        }

        if let image = NSImage(pasteboard: pasteboard),
           let tiff = image.tiffRepresentation,
           let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
            return ClipboardItem(id: UUID(), kind: .image, imageData: png, date: Date(), sourceBundleID: sourceBundleID)
        }

        return nil
    }

    private func insert(_ item: ClipboardItem) {
        items.removeAll { $0.hasSameContent(as: item) }
        items.insert(item, at: 0)
        trimToLimit()
        save()
    }

    private func trimToLimit() {
        let limit = max(1, Defaults[.clipboardHistoryLimit])
        if items.count > limit {
            items.removeLast(items.count - limit)
            save()
        }
    }

    // MARK: Actions

    /// Puts a clip back on the pasteboard and moves it to the top of the history.
    func copy(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text, .link:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .file:
            let urls = (item.filePaths ?? []).map { URL(fileURLWithPath: $0) as NSURL }
            pasteboard.writeObjects(urls)
        case .image:
            if let data = item.imageData, let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        }
        // Our own write should not be recorded as a new clip.
        lastChangeCount = pasteboard.changeCount

        if let index = items.firstIndex(where: { $0.id == item.id }) {
            let moved = items.remove(at: index)
            items.insert(moved, at: 0)
            save()
        }
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        save()
    }

    func clearAll() {
        items.removeAll()
        save()
    }

    // MARK: Persistence

    private func load() {
        guard let data = try? Data(contentsOf: fileURL),
              let stored = try? decoder.decode([ClipboardItem].self, from: data)
        else { return }
        items = stored
    }

    private func save() {
        let persistable = items.filter { $0.kind != .image }
        guard let data = try? encoder.encode(persistable) else { return }
        try? data.write(to: fileURL, options: .atomic)
    }
}
