//
//  ClipboardHistoryTests.swift
//  boringNotch
//
//  SPDX-License-Identifier: GPL-3.0-only
//

import AppKit

/// All fixtures are synthetic. These checks never read or write NSPasteboard.general.
@main
@MainActor
struct ClipboardHistoryTests {
    private static var assertions = 0

    static func main() {
        let board = NSPasteboard.withUniqueName()
        defer { board.releaseGlobally() }
        var source = ClipboardSourceApplication(name: "Synthetic Notes", bundleIdentifier: "com.apple.Notes")
        write("Synthetic prelaunch copy", to: board)
        let manager = ClipboardHistoryManager(pasteboard: board, sourceProvider: { source })
        manager.capturePasteboardChanges()
        expect(manager.items.isEmpty, "Do not import clipboard content that predates startup")

        write("Synthetic first\nsecond line", to: board)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1, "Capture text after the pasteboard changes")
        expect(manager.items[0].content.preview == "Synthetic first second line", "Preview stays on one line")
        expect(manager.items[0].matches("SECOND"), "Search all text case-insensitively")
        expect(manager.items[0].matches("notes"), "Search source app name")
        expect(manager.items[0].matches("com.apple"), "Search source bundle")
        expect(!manager.items[0].matches("Missing synthetic string"), "Reject unmatched search")
        let originalID = manager.items[0].id
        write("Synthetic first\nsecond line", to: board)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1 && manager.items[0].id == originalID, "Deduplicate equal payloads with stable identity")
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1, "Ignore an unchanged pasteboard")

        source = ClipboardSourceApplication(name: "Synthetic Browser", bundleIdentifier: "com.apple.Safari")
        write("https://example.com/synthetic", to: board, type: .URL)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Capture URL-only representations")
        guard case .text(_, let isURL) = manager.items[0].content else { fatalError("Expected URL content") }
        expect(isURL, "Retain URL semantics")
        let urlItem = manager.items[0]
        expect(manager.copy(urlItem), "Copy history item back successfully")
        expect(board.string(forType: .string) == "https://example.com/synthetic", "Copy-back supports plain-text paste")
        expect(board.string(forType: .URL) == "https://example.com/synthetic", "Copy-back preserves the URL representation")
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Suppress own writes with the generated marker")

        for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.SensitiveType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            write("Synthetic sensitive fixture", to: board, marker: marker)
            manager.capturePasteboardChanges()
            expect(manager.items.count == 2, "Exclude sensitive pasteboard marker")
        }
        source = ClipboardSourceApplication(name: "Synthetic Password Manager", bundleIdentifier: "com.bitwarden.desktop")
        write("Synthetic unmarked password-manager fixture", to: board)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Exclude known password-manager app source")
        source = ClipboardSourceApplication(name: "Synthetic Notes", bundleIdentifier: "com.apple.Notes")
        let declaredSourceItem = NSPasteboardItem()
        declaredSourceItem.setString("Synthetic declared password source", forType: .string)
        declaredSourceItem.setString("com.agilebits.onepassword7", forType: .init("org.nspasteboard.source"))
        board.clearContents()
        board.writeObjects([declaredSourceItem])
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Exclude a declared password source even after focus changes")

        write("  \n\t ", to: board)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Skip whitespace-only copies")
        write("Synthetic unsupported binary", to: board, type: .init("org.example.synthetic-binary"))
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Skip unsupported content")

        manager.setPaused(true)
        write("Synthetic paused copy", to: board)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Pause suppresses capture")
        manager.setPaused(false)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 2, "Resume does not import content copied while paused")
        write("Synthetic resumed copy", to: board)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 3, "Resume captures the next new copy")
        manager.delete(manager.items[0])
        expect(manager.items.count == 2, "Delete one item")
        manager.clearHistory()
        manager.capturePasteboardChanges()
        expect(manager.items.isEmpty, "Clear does not recapture unchanged clipboard content")
        expect(board.string(forType: .string) == "Synthetic resumed copy", "Clear history leaves system paste content intact")

        checkBounds(board)
        checkImages(board)
        checkWideImageThumbnail(board)
        checkRace(board)
        checkRecentCopies(board)
        manager.startMonitoring()
        manager.startMonitoring()
        expect(manager.isMonitoring, "Starting capture is idempotent")
        manager.stopMonitoring()
        expect(!manager.isMonitoring, "Stop invalidates capture")
        print("Clipboard history: \(assertions) assertions passed using synthetic fixtures and an isolated pasteboard.")
    }

    private static func checkBounds(_ board: NSPasteboard) {
        let bounded = ClipboardHistoryManager(pasteboard: board, maximumItems: 2, maximumTotalBytes: 8, maximumItemBytes: 5)
        for value in ["one", "two", "three"] {
            write(value, to: board)
            bounded.capturePasteboardChanges()
        }
        expect(bounded.items.count == 2 && bounded.items.last?.content.preview == "two", "Evict oldest items at the count limit")
        write("four", to: board)
        bounded.capturePasteboardChanges()
        expect(bounded.items.count == 1 && bounded.items[0].content.preview == "four", "Evict oldest items at the byte limit")
        write("Synthetic oversized payload", to: board)
        bounded.capturePasteboardChanges()
        expect(bounded.items.count == 1, "Reject oversized text")
    }

    private static func checkImages(_ board: NSPasteboard) {
        let manager = ClipboardHistoryManager(pasteboard: board)
        guard let bitmap = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 2, pixelsHigh: 2, bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0) else { fatalError("Cannot create synthetic bitmap") }
        let color = NSColor(deviceRed: 1, green: 0.5, blue: 0, alpha: 1)
        for x in 0..<2 { for y in 0..<2 { bitmap.setColor(color, atX: x, y: y) } }
        guard let png = bitmap.representation(using: .png, properties: [:]) else { fatalError("Cannot encode synthetic bitmap") }
        board.clearContents()
        board.setData(png, forType: .png)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1, "Capture a valid bounded PNG image")
        guard case .image(_, _, let thumbnail) = manager.items[0].content,
              let tinyImage = thumbnail.cgImage(forProposedRect: nil, context: nil, hints: nil) else {
            fatalError("Expected a decodable image thumbnail")
        }
        expect(tinyImage.width == 2 && tinyImage.height == 2, "Do not upscale small image thumbnails")
        expect(manager.items[0].matches("image"), "Find images by type")
        expect(manager.copy(manager.items[0]), "Copy an image back")
        expect(board.data(forType: .png) == png, "Preserve original image bytes on paste")
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1, "Suppress duplicate image copy-back")
        board.clearContents()
        board.setData(Data("Synthetic invalid image".utf8), forType: .png)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1, "Reject invalid image data")
    }

    private static func checkWideImageThumbnail(_ board: NSPasteboard) {
        let manager = ClipboardHistoryManager(pasteboard: board)
        guard let bitmap = NSBitmapImageRep(
            bitmapDataPlanes: nil, pixelsWide: 800, pixelsHigh: 200,
            bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
            isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0
        ) else { fatalError("Could not create synthetic wide image") }
        for x in 0..<800 {
            for y in 0..<200 {
                // Thin strokes model the equation images that lose detail in small thumbnails.
                bitmap.setColor(y % 40 < 4 || x % 100 < 4 ? .white : .black, atX: x, y: y)
            }
        }
        guard let png = bitmap.representation(using: .png, properties: [:]) else {
            fatalError("Could not encode synthetic wide image")
        }
        board.clearContents()
        board.setData(png, forType: .png)
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1, "Capture a wide image with thin strokes")
        guard case .image(let original, let type, let thumbnail) = manager.items[0].content,
              let image = thumbnail.cgImage(forProposedRect: nil, context: nil, hints: nil) else {
            fatalError("Expected a decodable wide image thumbnail")
        }
        expect(image.width == 320 && image.height == 80, "Retain Retina thumbnail detail and the original aspect ratio")
        expect(original == png && type == .png, "Thumbnail generation preserves original encoded image data")
        expect(manager.copy(manager.items[0]), "Copy the original wide image successfully")
        expect(board.data(forType: .png) == png, "Copy full-resolution original bytes instead of the thumbnail")
    }

    private static func checkRecentCopies(_ board: NSPasteboard) {
        let manager = ClipboardHistoryManager(pasteboard: board)
        manager.startMonitoring()
        defer { manager.stopMonitoring() }
        expect(!manager.hasRecentCopies(), "Empty history does not open the clipboard on hover")
        write("Synthetic recent first", to: board)
        manager.capturePasteboardChanges()
        expect(!manager.hasRecentCopies(), "One recent item does not open the clipboard on hover")
        write("Synthetic recent first", to: board)
        manager.capturePasteboardChanges()
        expect(!manager.hasRecentCopies(), "Repeated copies of one item do not count as two items")
        write("Synthetic concealed recent item", to: board, marker: "org.nspasteboard.ConcealedType")
        manager.capturePasteboardChanges()
        expect(!manager.hasRecentCopies(), "Excluded copies do not influence hover routing")
        write("Synthetic recent second", to: board)
        manager.capturePasteboardChanges()
        expect(manager.hasRecentCopies(), "Two recent detected items open the clipboard on hover")
        let oldest = manager.items[1].capturedAt
        expect(manager.hasRecentCopies(at: oldest.addingTimeInterval(30)),
               "Include two items within the thirty-second window")
        expect(!manager.hasRecentCopies(at: oldest.addingTimeInterval(30.001)),
               "Expire the rule when only one item is recent")
        expect(!manager.hasRecentCopies(at: oldest.addingTimeInterval(-1)),
               "Ignore future timestamps after a clock change")
        manager.setPaused(true)
        expect(!manager.hasRecentCopies(), "Paused capture does not override the default hover pane")
        manager.setPaused(false)
        expect(manager.hasRecentCopies(), "Resumed capture uses the existing recent detection timestamps")
        manager.stopMonitoring()
        expect(!manager.hasRecentCopies(), "Stopped capture does not override the default hover pane")
        manager.startMonitoring()
        manager.delete(manager.items[0])
        expect(!manager.hasRecentCopies(), "Deleted items do not count toward the hover rule")
        manager.clearHistory()
        expect(!manager.hasRecentCopies(), "Cleared history does not keep an automatic clipboard override")
    }

    private static func checkRace(_ board: NSPasteboard) {
        var shouldReplace = true
        let manager = ClipboardHistoryManager(pasteboard: board, sourceProvider: {
            if shouldReplace {
                shouldReplace = false
                write("Synthetic replacement", to: board)
            }
            return ClipboardSourceApplication(name: "Synthetic App", bundleIdentifier: nil)
        })
        write("Synthetic replaced copy", to: board)
        manager.capturePasteboardChanges()
        expect(manager.items.isEmpty, "Discard an inconsistent read when changeCount changes mid-capture")
        manager.capturePasteboardChanges()
        expect(manager.items.count == 1 && manager.items[0].content.preview == "Synthetic replacement", "Capture the replacement on the next stable read")
    }

    private static func write(_ value: String, to board: NSPasteboard, type: NSPasteboard.PasteboardType = .string, marker: String? = nil) {
        let item = NSPasteboardItem()
        item.setString(value, forType: type)
        if let marker { item.setData(Data(), forType: .init(marker)) }
        board.clearContents()
        precondition(board.writeObjects([item]))
    }

    private static func expect(_ condition: @autoclosure () -> Bool, _ label: String) {
        assertions += 1
        precondition(condition(), label)
    }
}
