//
//  BrowserBridgeServer.swift
//  boringNotch
//
//  Loopback WebSocket server that the Boring Notch browser extension connects to.
//
//  A Chrome extension cannot listen on a socket, so the app has to be the server and
//  the extension the client. `NWProtocolWebSocket` gives us RFC 6455 for free, so this
//  needs no third-party dependency, and `com.apple.security.network.server` is already
//  in the app's entitlements.
//
//  The listener is bound to 127.0.0.1 only. That still leaves it reachable by any local
//  process (including any web page), so a shared token — generated by the app and pasted
//  into the extension by the user — is what actually authorises a client.
//

import Foundation
import Network
import os

actor BrowserBridgeServer {
    /// Wraps a connection so a stale receive loop can tell whether it has been superseded
    /// by identity rather than by some flag that could race.
    ///
    /// `@unchecked Sendable` because the two mutable properties are only ever read or
    /// written from inside `BrowserBridgeServer`'s actor isolation; the network callbacks
    /// that capture instances of this type only pass them back to the actor.
    private final class ClientConnection: @unchecked Sendable {
        let connection: NWConnection
        var isAuthenticated = false
        var suppressDisconnectCallback = false

        init(connection: NWConnection) {
            self.connection = connection
        }
    }

    private let configuration: BrowserBridgeConfiguration
    private let token: String
    private var listener: NWListener?
    /// The authenticated client, if any.
    private var client: ClientConnection?
    /// Connections that have arrived but not yet proved they know the token. They are
    /// kept separate so an unauthenticated peer cannot displace a working extension.
    private var pending: [ClientConnection] = []

    /// Bounds how many unauthenticated sockets we will hold open at once.
    private static let maxPendingConnections = 8

    private let queue = DispatchQueue(label: "boringnotch.browserbridge", qos: .userInitiated)
    private static let logger = Logger(subsystem: "theboringteam.boringnotch", category: "BrowserBridge")

    private let decoder = JSONDecoder()
    private let encoder = JSONEncoder()

    /// Read synchronously (and off-actor) by `isActive()`, which the media controller
    /// protocol requires to be non-async.
    private let liveness = BrowserBridgeLiveness()

    private var onState: (@Sendable (BrowserBridgeTrackState) -> Void)?
    private var onConnectionChange: (@Sendable (Bool) -> Void)?

    init(configuration: BrowserBridgeConfiguration = .default, token: String) {
        self.configuration = configuration
        self.token = token
    }

    /// Shared with the controller so `isActive()` can answer without awaiting the actor.
    nonisolated var livenessProbe: BrowserBridgeLiveness { liveness }

    func setHandlers(
        onState: @escaping @Sendable (BrowserBridgeTrackState) -> Void,
        onConnectionChange: @escaping @Sendable (Bool) -> Void
    ) {
        self.onState = onState
        self.onConnectionChange = onConnectionChange
    }

    // MARK: - Lifecycle

    func start() throws {
        guard listener == nil else { return }

        let parameters = NWParameters.tcp
        parameters.allowLocalEndpointReuse = true
        // Binding the local endpoint to the loopback address keeps the listener off every
        // other interface, so nothing on the network can reach it.
        parameters.requiredLocalEndpoint = .hostPort(
            host: .ipv4(.loopback),
            port: NWEndpoint.Port(rawValue: configuration.port) ?? .any
        )

        let websocket = NWProtocolWebSocket.Options()
        websocket.autoReplyPing = true
        parameters.defaultProtocolStack.applicationProtocols.insert(websocket, at: 0)

        let newListener: NWListener
        do {
            newListener = try NWListener(using: parameters)
        } catch {
            throw BrowserBridgeError.listenerFailed(error.localizedDescription)
        }

        newListener.stateUpdateHandler = { [weak self] state in
            switch state {
            case .ready:
                Self.logger.info("Browser bridge listening on 127.0.0.1")
            case .failed(let error):
                Self.logger.error("Browser bridge listener failed: \(error.localizedDescription)")
                Task { await self?.handleListenerFailure() }
            case .cancelled:
                break
            default:
                break
            }
        }

        newListener.newConnectionHandler = { [weak self] connection in
            Task { await self?.accept(connection) }
        }

        listener = newListener
        newListener.start(queue: queue)
    }

    func stop() {
        listener?.stateUpdateHandler = nil
        listener?.newConnectionHandler = nil
        listener?.cancel()
        listener = nil
        disconnectClient()
        liveness.clear()
    }

    private func handleListenerFailure() {
        listener?.cancel()
        listener = nil
        liveness.clear()
        onConnectionChange?(false)
    }

    // MARK: - Client handling

    private func accept(_ connection: NWConnection) {
        // Arrivals start out unauthenticated. Crucially they do NOT displace the current
        // client yet — otherwise any local process could kick the real extension off
        // simply by opening a socket.
        let incoming = ClientConnection(connection: connection)

        if pending.count >= Self.maxPendingConnections, let oldest = pending.first {
            close(oldest)
        }
        pending.append(incoming)

        connection.stateUpdateHandler = { [weak self] state in
            switch state {
            case .ready:
                Task { await self?.receive(on: incoming) }
            case .failed, .cancelled:
                Task { await self?.handleDisconnect(of: incoming) }
            default:
                break
            }
        }

        connection.start(queue: queue)
    }

    /// Tears a connection down without reporting it as a client disconnect.
    private func close(_ connection: ClientConnection) {
        connection.suppressDisconnectCallback = true
        connection.connection.stateUpdateHandler = nil
        connection.connection.cancel()
        pending.removeAll { $0 === connection }
        if client === connection { client = nil }
    }

    private func disconnectClient() {
        if let current = client { close(current) }
        for connection in pending { close(connection) }
        pending.removeAll()
    }

    /// Called once a connection presents the right token. Only here does it become the
    /// active client, replacing whatever was there before.
    private func promote(_ connection: ClientConnection) {
        pending.removeAll { $0 === connection }

        if let previous = client, previous !== connection {
            close(previous)
        }

        connection.isAuthenticated = true
        client = connection
        liveness.markAlive()
    }

    private func handleDisconnect(of connection: ClientConnection) {
        pending.removeAll { $0 === connection }

        // A pending connection dropping is not a client disconnect.
        guard client === connection else { return }
        client = nil
        liveness.clear()
        if !connection.suppressDisconnectCallback {
            onConnectionChange?(false)
        }
    }

    private func isKnown(_ connection: ClientConnection) -> Bool {
        client === connection || pending.contains { $0 === connection }
    }

    private func receive(on connection: ClientConnection) {
        guard isKnown(connection) else { return }

        connection.connection.receiveMessage { [weak self] data, context, _, error in
            guard let self else { return }

            if let error {
                Self.logger.debug("Browser bridge receive error: \(error.localizedDescription)")
                Task { await self.handleDisconnect(of: connection) }
                return
            }

            // A close frame means the extension is going away deliberately.
            if let metadata = context?.protocolMetadata(definition: NWProtocolWebSocket.definition)
                as? NWProtocolWebSocket.Metadata, metadata.opcode == .close {
                Task { await self.handleDisconnect(of: connection) }
                return
            }

            if let data, !data.isEmpty {
                Task { await self.handle(data, from: connection) }
            }

            Task { await self.receive(on: connection) }
        }
    }

    private func handle(_ data: Data, from connection: ClientConnection) {
        guard isKnown(connection) else { return }

        guard let message = try? decoder.decode(BrowserBridgeInboundMessage.self, from: data) else {
            Self.logger.debug("Browser bridge received an undecodable message")
            return
        }

        switch message.type {
        case .hello:
            // An exact match is required. Constant-time comparison isn't warranted: a
            // local attacker able to time this already has far better options.
            guard let provided = message.token, !provided.isEmpty, provided == token else {
                Self.logger.error("Browser bridge rejected a client with an invalid token")
                send(.error("unauthorized"), on: connection)
                // Let the frame flush, then drop it. The active client is untouched.
                queue.asyncAfter(deadline: .now() + 0.25) { [weak self] in
                    Task { await self?.close(connection) }
                }
                return
            }
            promote(connection)
            Self.logger.info("Browser bridge client authenticated")
            send(.welcome(), on: connection)
            onConnectionChange?(true)

        case .ping:
            guard connection.isAuthenticated, client === connection else { return }
            liveness.markAlive()
            send(.pong(), on: connection)

        case .state:
            guard connection.isAuthenticated, client === connection,
                  let state = message.state else { return }
            liveness.markAlive()
            onState?(state)

        case .bye:
            let wasClient = client === connection
            close(connection)
            if wasClient {
                liveness.clear()
                onConnectionChange?(false)
            }
        }
    }

    // MARK: - Sending

    func send(_ command: BrowserBridgeCommand, value: Double? = nil) {
        guard let client, client.isAuthenticated else { return }
        send(.command(command, value: value), on: client)
    }

    private func send(_ message: BrowserBridgeOutboundMessage, on connection: ClientConnection) {
        guard let data = try? encoder.encode(message) else {
            Self.logger.error("Browser bridge failed to encode \(message.type)")
            return
        }

        let metadata = NWProtocolWebSocket.Metadata(opcode: .text)
        let context = NWConnection.ContentContext(identifier: "bridge", metadata: [metadata])

        connection.connection.send(
            content: data,
            contentContext: context,
            isComplete: true,
            completion: .contentProcessed { error in
                if let error {
                    Self.logger.debug("Browser bridge send failed: \(error.localizedDescription)")
                }
            }
        )
    }
}

/// Thread-safe last-seen timestamp.
///
/// `MediaControllerProtocol.isActive()` is synchronous and non-isolated, so it cannot
/// await the server actor. This gives it something cheap and safe to read instead.
final class BrowserBridgeLiveness: @unchecked Sendable {
    private let lock = NSLock()
    private var lastSeen: Date?
    private let timeout: TimeInterval

    init(timeout: TimeInterval = BrowserBridgeConfiguration.default.clientTimeout) {
        self.timeout = timeout
    }

    func markAlive() {
        lock.lock()
        lastSeen = Date()
        lock.unlock()
    }

    func clear() {
        lock.lock()
        lastSeen = nil
        lock.unlock()
    }

    var isAlive: Bool {
        lock.lock()
        defer { lock.unlock() }
        guard let lastSeen else { return false }
        return Date().timeIntervalSince(lastSeen) < timeout
    }
}
