---
name: Bug Report
description: File a bug report.
title: '[Bug] '
labels:
  - bug
  - unconfirmed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? What are the steps to reproduce the issue?
      description: >-
        Describe the bug and include the steps to replicate the issue. Issues
        with images or videos will be resolved faster.
      placeholder: Clearly explain the issue. Please limit each post to one issue.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Boring Notch Version
      description: >-
        What version of our software are you running? (Go to ✦ in the menu bar >
        Settings > About)
      options:
        - Select a version
        - v2.7.3
        - v2.7.2
        - v2.7.1
        - v2.7
        - v2.7-rc.3
        - v2.6
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: macOS Version
      description: Go to  > About This Mac
    validations:
      required: true
  - type: dropdown
    id: music-source
    attributes:
      label: Music Source? (If relevant)
      description: >-
         If this issue is related to music, what music source did you select in Boring Notch settings?
      options:
        - Now Playing
        - Apple Music
        - Spotify
        - YouTube Music
    validations:
      required: false
  - type: input
    id: music-app
    attributes:
      label: Music App (If using Now Playing)
    validations:
      required: false
  - type: input
    id: music-website
    attributes:
      label: Website (If using browser for music)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >-
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: 
      options:
        - label: I haven't found any duplicates with my issue.
          required: true
