import AppKit
import Defaults
import Foundation

nonisolated enum ClipboardPrivacyFilter {
    static func isSensitivePasteboardType(_ rawValue: String) -> Bool {
        let sensitiveFragments = ["concealed", "transient", "password", "autogenerated"]
        let normalized = rawValue.lowercased()
        return sensitiveFragments.contains { normalized.contains($0) }
    }

    static func looksSensitive(_ text: String) -> Bool {
        let lowercased = text.lowercased()
        let secretMarkers = [
            "-----begin private key-----",
            "-----begin rsa private key-----",
            "aws_secret_access_key",
            "client_secret=",
        ]
        if secretMarkers.contains(where: lowercased.contains) { return true }

        let tokenPatterns = [
            #"\bAKIA[0-9A-Z]{16}\b"#,
            #"\bgh[pousr]_[A-Za-z0-9_]{30,}\b"#,
            #"\bsk-[A-Za-z0-9_-]{20,}\b"#,
        ]
        return tokenPatterns.contains { pattern in
            text.range(of: pattern, options: .regularExpression) != nil
        }
    }
}

@MainActor
final class ClipboardHistoryManager: ObservableObject {
    static let shared = ClipboardHistoryManager()

    @Published private(set) var entries: [ClipboardHistoryEntry] = []
    @Published private(set) var isMonitoring = false

    private let pasteboard = NSPasteboard.general
    private var monitoringTask: Task<Void, Never>?
    private var lastChangeCount: Int
    private let persistenceURL: URL

    private init(fileManager: FileManager = .default) {
        lastChangeCount = pasteboard.changeCount
        let support = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? fileManager.temporaryDirectory
        persistenceURL = support
            .appendingPathComponent("theboringteam.boringnotch", isDirectory: true)
            .appendingPathComponent("clipboard-history.json")

        if Defaults[.persistClipboardHistory] {
            loadPersistedEntries()
        }
        if Defaults[.clipboardHistoryEnabled] {
            startMonitoring()
        }
    }

    deinit {
        monitoringTask?.cancel()
    }

    func startMonitoring() {
        guard monitoringTask == nil else { return }
        isMonitoring = true
        lastChangeCount = pasteboard.changeCount

        monitoringTask = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                self?.captureClipboardIfChanged()
                try? await Task.sleep(for: .milliseconds(600))
            }
        }
    }

    func stopMonitoring() {
        monitoringTask?.cancel()
        monitoringTask = nil
        isMonitoring = false
    }

    func refreshConfiguration() {
        if Defaults[.clipboardHistoryEnabled] {
            if Defaults[.persistClipboardHistory], entries.isEmpty {
                loadPersistedEntries()
            }
            startMonitoring()
        } else {
            stopMonitoring()
        }

        if !Defaults[.persistClipboardHistory] {
            try? FileManager.default.removeItem(at: persistenceURL)
        } else {
            persistEntries()
        }
        pruneEntries()
    }

    func copy(_ entry: ClipboardHistoryEntry) {
        pasteboard.clearContents()
        pasteboard.writeObjects([entry.text as NSString])
        lastChangeCount = pasteboard.changeCount
    }

    func remove(_ entry: ClipboardHistoryEntry) {
        entries.removeAll { $0.id == entry.id }
        persistEntriesIfNeeded()
    }

    func clear() {
        entries = []
        try? FileManager.default.removeItem(at: persistenceURL)
    }

    private func captureClipboardIfChanged() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let sourceBundleIdentifier = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        guard !isExcludedSource(sourceBundleIdentifier), !containsSensitivePasteboardType() else { return }
        guard let text = pasteboard.string(forType: .string) else { return }

        let normalized = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty, normalized.count <= 20_000,
              !ClipboardPrivacyFilter.looksSensitive(normalized) else { return }

        entries.removeAll { $0.text == normalized }
        entries.insert(
            ClipboardHistoryEntry(
                id: UUID(),
                text: normalized,
                copiedAt: Date(),
                sourceBundleIdentifier: sourceBundleIdentifier
            ),
            at: 0
        )
        pruneEntries()
        persistEntriesIfNeeded()
    }

    private func pruneEntries() {
        let retention = TimeInterval(max(1, Defaults[.clipboardRetentionHours])) * 3600
        let cutoff = Date().addingTimeInterval(-retention)
        let maximumCount = min(max(1, Defaults[.clipboardMaximumItemCount]), 100)
        entries = Array(entries.filter { $0.copiedAt >= cutoff }.prefix(maximumCount))
    }

    private func isExcludedSource(_ bundleIdentifier: String?) -> Bool {
        guard let bundleIdentifier else { return false }
        return Defaults[.clipboardExcludedBundleIdentifiers].contains(bundleIdentifier)
            || bundleIdentifier == Bundle.main.bundleIdentifier
    }

    private func containsSensitivePasteboardType() -> Bool {
        return (pasteboard.types ?? []).contains {
            ClipboardPrivacyFilter.isSensitivePasteboardType($0.rawValue)
        }
    }

    private func loadPersistedEntries() {
        guard let data = try? Data(contentsOf: persistenceURL),
              let decoded = try? JSONDecoder().decode([ClipboardHistoryEntry].self, from: data)
        else { return }
        entries = decoded
        pruneEntries()
    }

    private func persistEntriesIfNeeded() {
        guard Defaults[.persistClipboardHistory] else { return }
        persistEntries()
    }

    private func persistEntries() {
        do {
            let directory = persistenceURL.deletingLastPathComponent()
            try FileManager.default.createDirectory(
                at: directory,
                withIntermediateDirectories: true,
                attributes: [.posixPermissions: 0o700]
            )
            let data = try JSONEncoder().encode(entries)
            try data.write(to: persistenceURL, options: [.atomic, .completeFileProtection])
        } catch {
            NSLog("Failed to persist clipboard history: %@", error.localizedDescription)
        }
    }
}
