//
//  ClipboardHistoryViewModel.swift
//  boringNotch
//

import AppKit
import Combine
import CryptoKit
import Defaults
import Foundation
import SwiftUI

private extension NSPasteboard.PasteboardType {
    static let clipboardPNG = NSPasteboard.PasteboardType("public.png")
    static let clipboardJPEG = NSPasteboard.PasteboardType("public.jpeg")
}

private struct ClipboardImageSnapshot: Sendable {
    let data: Data
    let typeIdentifier: String
    let sourceName: String?
    let sourceBundleIdentifier: String?
}

private struct ProcessedClipboardImage: Sendable {
    let pngData: Data
    let hash: String
    let width: Int?
    let height: Int?
}

private enum ClipboardHistoryConfiguration {
    static let pollInterval: TimeInterval = 0.75
    static let thumbnailPixelSize = 132
    static let privatePasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]
}

@MainActor
final class ClipboardHistoryViewModel: ObservableObject {
    static let shared = ClipboardHistoryViewModel()

    @Published private(set) var items: [ClipboardHistoryItem]
    @Published private(set) var visibleItems: [ClipboardHistoryItem] = []
    @Published private(set) var sections: [ClipboardHistorySection] = []
    @Published var searchText = "" {
        didSet { rebuildVisibleItems() }
    }
    @Published var selectedFilter: ClipboardHistoryFilter = .all {
        didSet { rebuildVisibleItems() }
    }
    @Published private(set) var copiedItemID: UUID?
    @Published private(set) var isUserPaused = false
    @Published private(set) var isSystemPaused = false
    @Published private(set) var isMonitoring = false
    @Published private(set) var storageByteCount = 0

    private let store: ClipboardHistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int
    private var ignoredChangeCount: Int?
    private let thumbnailCache = NSCache<NSString, NSImage>()
    private let sourceIconCache = NSCache<NSString, NSImage>()
    private var missingSourceIconBundleIDs = Set<String>()
    private var captureGeneration = 0

    private init(store: ClipboardHistoryStore = .shared) {
        self.store = store
        self.items = store.load().filter { item in
            item.kind != .image || store.imageExists(for: item)
        }
        self.lastChangeCount = NSPasteboard.general.changeCount
        self.storageByteCount = Self.imageByteCount(in: items)
        store.pruneOrphanedImages(keeping: items)
        rebuildVisibleItems()
    }

    var statusText: String {
        if !Defaults[.clipboardHistoryEnabled] {
            return "Off"
        }
        if isSystemPaused {
            return "Paused on lock"
        }
        if isUserPaused {
            return "Paused"
        }
        return "Recording"
    }

    var storageText: String {
        ByteCountFormatter.string(fromByteCount: Int64(storageByteCount), countStyle: .file)
    }

    func start() {
        reconcileMonitoringTimer()
    }

    func enableHistory() {
        Defaults[.clipboardHistoryEnabled] = true
        lastChangeCount = NSPasteboard.general.changeCount
        reconcileMonitoringTimer()
    }

    func disableHistory() {
        Defaults[.clipboardHistoryEnabled] = false
        reconcileMonitoringTimer()
    }

    func toggleUserPaused() {
        isUserPaused.toggle()
        if !isUserPaused {
            lastChangeCount = NSPasteboard.general.changeCount
        }
        reconcileMonitoringTimer()
    }

    func setSystemPaused(_ paused: Bool) {
        isSystemPaused = paused && Defaults[.clipboardHistoryPauseOnLock]
        if !isSystemPaused {
            lastChangeCount = NSPasteboard.general.changeCount
        }
        reconcileMonitoringTimer()
    }

    func copy(_ item: ClipboardHistoryItem) {
        let pasteboard = NSPasteboard.general

        switch item.kind {
        case .text:
            let string = item.text ?? ""
            pasteboard.clearContents()
            guard pasteboard.setString(string, forType: .string) else { return }
        case .image:
            guard let data = store.imageData(for: item) else { return }
            let pasteboardItem = NSPasteboardItem()
            pasteboardItem.setData(data, forType: .clipboardPNG)
            pasteboard.clearContents()
            guard pasteboard.writeObjects([pasteboardItem]) else { return }
        }

        ignoredChangeCount = pasteboard.changeCount
        copiedItemID = item.id
        Task { [weak self] in
            try? await Task.sleep(for: .seconds(1.2))
            guard !Task.isCancelled else { return }
            await MainActor.run {
                if self?.copiedItemID == item.id {
                    self?.copiedItemID = nil
                }
            }
        }
    }

    func togglePinned(_ item: ClipboardHistoryItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        rebuildVisibleItems()
        persist()
    }

    func remove(_ item: ClipboardHistoryItem) {
        if item.kind == .image {
            store.removeImage(for: item)
            removeCachedThumbnail(for: item)
        }
        items.removeAll { $0.id == item.id }
        rebuildVisibleItems()
        persist()
    }

    func clear() {
        captureGeneration += 1
        items.removeAll()
        rebuildVisibleItems()
        thumbnailCache.removeAllObjects()
        store.clearAll()
        storageByteCount = 0
    }

    func enforceRetentionLimits() {
        pruneIfNeeded()
        rebuildVisibleItems()
        persist()
    }

    func thumbnail(for item: ClipboardHistoryItem) -> NSImage? {
        let key = cacheKey(for: item)
        if let cached = thumbnailCache.object(forKey: key) {
            return cached
        }
        guard let image = store.thumbnail(for: item, maxPixelSize: ClipboardHistoryConfiguration.thumbnailPixelSize) else {
            return nil
        }
        thumbnailCache.setObject(image, forKey: key)
        return image
    }

    func sourceIcon(for item: ClipboardHistoryItem) -> NSImage? {
        guard Defaults[.clipboardHistoryShowSourceApps],
              let bundleID = item.sourceBundleIdentifier else {
            return nil
        }
        let key = NSString(string: bundleID)
        if let cached = sourceIconCache.object(forKey: key) {
            return cached
        }
        guard !missingSourceIconBundleIDs.contains(bundleID),
              let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) else {
            missingSourceIconBundleIDs.insert(bundleID)
            return nil
        }
        let icon = NSWorkspace.shared.icon(forFile: url.path)
        sourceIconCache.setObject(icon, forKey: key)
        return icon
    }

    private func pollPasteboard() {
        guard Defaults[.clipboardHistoryEnabled], !isUserPaused, !isSystemPaused else { return }

        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        if changeCount == ignoredChangeCount {
            ignoredChangeCount = nil
            return
        }

        guard !containsPrivatePasteboardTypes(pasteboard) else { return }

        captureGeneration += 1
        let generation = captureGeneration
        let source = sourceApplication()
        if Defaults[.clipboardHistoryCaptureImages], captureImage(from: pasteboard, source: source, generation: generation) {
            return
        }
        captureText(from: pasteboard, source: source)
    }

    private func captureText(from pasteboard: NSPasteboard, source: (name: String?, bundleIdentifier: String?)) {
        guard let string = pasteboard.string(forType: .string) else { return }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let data = Data(string.utf8)
        let hash = hashString(for: data, prefix: "text")

        if promoteExistingItem(withHash: hash, source: source) {
            return
        }

        let item = ClipboardHistoryItem(
            kind: .text,
            hash: hash,
            text: string,
            sourceAppName: source.name,
            sourceBundleIdentifier: source.bundleIdentifier
        )
        insert(item)
    }

    private func captureImage(
        from pasteboard: NSPasteboard,
        source: (name: String?, bundleIdentifier: String?),
        generation: Int
    ) -> Bool {
        let types = pasteboard.types ?? []
        guard let snapshot = imageSnapshot(from: pasteboard, types: types, source: source) else {
            return false
        }

        Task.detached(priority: .utility) { [store] in
            guard let processed = Self.processImage(snapshot) else { return }
            let shouldStore = await MainActor.run {
                guard self.captureGeneration == generation else { return false }
                let source = (name: snapshot.sourceName, bundleIdentifier: snapshot.sourceBundleIdentifier)
                return !self.promoteExistingItem(withHash: processed.hash, source: source)
            }
            guard shouldStore else { return }

            let filename = "\(UUID().uuidString).png"
            guard let storedFilename = store.storeImageData(processed.pngData, filename: filename) else { return }

            await MainActor.run {
                guard self.captureGeneration == generation else {
                    store.removeImage(named: storedFilename)
                    return
                }
                let item = ClipboardHistoryItem(
                    kind: .image,
                    hash: processed.hash,
                    imageFilename: storedFilename,
                    imageWidth: processed.width,
                    imageHeight: processed.height,
                    imageByteCount: processed.pngData.count,
                    sourceAppName: snapshot.sourceName,
                    sourceBundleIdentifier: snapshot.sourceBundleIdentifier
                )
                self.insert(item)
            }
        }
        return true
    }

    private func promoteExistingItem(withHash hash: String, source: (name: String?, bundleIdentifier: String?)) -> Bool {
        guard let index = items.firstIndex(where: { $0.hash == hash }) else { return false }
        var item = items.remove(at: index)
        item.createdAt = Date()
        item.sourceAppName = source.name ?? item.sourceAppName
        item.sourceBundleIdentifier = source.bundleIdentifier ?? item.sourceBundleIdentifier
        items.insert(item, at: 0)
        rebuildVisibleItems()
        persist()
        return true
    }

    private func insert(_ item: ClipboardHistoryItem) {
        items.insert(item, at: 0)
        pruneIfNeeded()
        rebuildVisibleItems()
        persist()
    }

    private func pruneIfNeeded() {
        let maxItems = max(10, Defaults[.clipboardHistoryMaxItems])
        while items.count > maxItems {
            guard let index = items.lastIndex(where: { !$0.isPinned }) ?? items.indices.last else { break }
            let item = items.remove(at: index)
            if item.kind == .image {
                store.removeImage(for: item)
                removeCachedThumbnail(for: item)
            }
        }

        let maxBytes = max(25, Defaults[.clipboardHistoryMaxStorageMB]) * 1024 * 1024
        storageByteCount = Self.imageByteCount(in: items)
        while storageByteCount > maxBytes {
            guard let index = items.lastIndex(where: { $0.kind == .image }) else { break }
            let item = items.remove(at: index)
            store.removeImage(for: item)
            removeCachedThumbnail(for: item)
            storageByteCount = Self.imageByteCount(in: items)
        }
    }

    private func persist() {
        store.save(items)
        storageByteCount = Self.imageByteCount(in: items)
    }

    private func reconcileMonitoringTimer() {
        let shouldMonitor = Defaults[.clipboardHistoryEnabled] && !isUserPaused && !isSystemPaused
        updateMonitoringState(shouldMonitor)

        if shouldMonitor {
            startTimerIfNeeded()
        } else {
            stopTimer()
        }
    }

    private func startTimerIfNeeded() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: ClipboardHistoryConfiguration.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.pollPasteboard()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func stopTimer() {
        timer?.invalidate()
        timer = nil
    }

    private func updateMonitoringState(_ newValue: Bool) {
        if isMonitoring != newValue {
            isMonitoring = newValue
        }
    }

    private func containsPrivatePasteboardTypes(_ pasteboard: NSPasteboard) -> Bool {
        (pasteboard.types ?? []).contains { ClipboardHistoryConfiguration.privatePasteboardTypes.contains($0.rawValue) }
    }

    private func sourceApplication() -> (name: String?, bundleIdentifier: String?) {
        let app = NSWorkspace.shared.frontmostApplication
        return (app?.localizedName, app?.bundleIdentifier)
    }

    nonisolated private static func hashString(for data: Data, prefix: String) -> String {
        let digest = SHA256.hash(data: data)
        return prefix + ":" + digest.map { String(format: "%02x", $0) }.joined()
    }

    private static func imageByteCount(in items: [ClipboardHistoryItem]) -> Int {
        items.reduce(0) { total, item in
            total + (item.kind == .image ? (item.imageByteCount ?? 0) : 0)
        }
    }

    private func hashString(for data: Data, prefix: String) -> String {
        Self.hashString(for: data, prefix: prefix)
    }

    private func rebuildVisibleItems() {
        let query = searchText.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        let filtered = items.filter { item in
            guard matchesSelectedFilter(item) else { return false }
            guard !query.isEmpty else { return true }
            return item.previewTitle.lowercased().contains(query)
                || item.detailText.lowercased().contains(query)
                || (item.sourceAppName?.lowercased().contains(query) ?? false)
        }

        visibleItems = filtered
        sections = Self.sections(from: filtered)
    }

    private func matchesSelectedFilter(_ item: ClipboardHistoryItem) -> Bool {
        switch selectedFilter {
        case .all:
            return true
        case .text:
            return item.kind == .text
        case .images:
            return item.kind == .image
        case .pinned:
            return item.isPinned
        }
    }

    private static func sections(from items: [ClipboardHistoryItem]) -> [ClipboardHistorySection] {
        var result: [ClipboardHistorySection] = []
        var currentTitle: String?
        var currentItems: [ClipboardHistoryItem] = []
        let calendar = Calendar.current

        for item in items {
            let title = sectionTitle(for: item.createdAt, calendar: calendar)
            if currentTitle == nil {
                currentTitle = title
            }
            if currentTitle != title {
                if let currentTitle {
                    result.append(ClipboardHistorySection(title: currentTitle, items: currentItems))
                }
                currentTitle = title
                currentItems.removeAll(keepingCapacity: true)
            }
            currentItems.append(item)
        }

        if let currentTitle {
            result.append(ClipboardHistorySection(title: currentTitle, items: currentItems))
        }
        return result
    }

    private static func sectionTitle(for date: Date, calendar: Calendar) -> String {
        if calendar.isDateInToday(date) {
            return "Today"
        }
        if calendar.isDateInYesterday(date) {
            return "Yesterday"
        }
        return date.formatted(.dateTime.month(.abbreviated).day().year())
    }

    private func cacheKey(for item: ClipboardHistoryItem) -> NSString {
        NSString(string: item.id.uuidString)
    }

    private func removeCachedThumbnail(for item: ClipboardHistoryItem) {
        thumbnailCache.removeObject(forKey: cacheKey(for: item))
    }

    private func imageSnapshot(
        from pasteboard: NSPasteboard,
        types: [NSPasteboard.PasteboardType],
        source: (name: String?, bundleIdentifier: String?)
    ) -> ClipboardImageSnapshot? {
        let preferredTypes: [NSPasteboard.PasteboardType] = [.clipboardPNG, .clipboardJPEG, .tiff]
        for type in preferredTypes where types.contains(type) {
            if let data = pasteboard.data(forType: type) {
                return ClipboardImageSnapshot(
                    data: data,
                    typeIdentifier: type.rawValue,
                    sourceName: source.name,
                    sourceBundleIdentifier: source.bundleIdentifier
                )
            }
        }

        guard types.contains(where: { $0.rawValue.hasPrefix("public.") }),
              let image = NSImage(pasteboard: pasteboard),
              let data = image.tiffRepresentation else {
            return nil
        }
        return ClipboardImageSnapshot(
            data: data,
            typeIdentifier: NSPasteboard.PasteboardType.tiff.rawValue,
            sourceName: source.name,
            sourceBundleIdentifier: source.bundleIdentifier
        )
    }

    nonisolated private static func processImage(_ snapshot: ClipboardImageSnapshot) -> ProcessedClipboardImage? {
        guard let bitmap = NSBitmapImageRep(data: snapshot.data) else { return nil }
        let pngData: Data
        if snapshot.typeIdentifier == NSPasteboard.PasteboardType.clipboardPNG.rawValue {
            pngData = snapshot.data
        } else {
            guard let converted = bitmap.representation(using: .png, properties: [:]) else { return nil }
            pngData = converted
        }
        return ProcessedClipboardImage(
            pngData: pngData,
            hash: hashString(for: pngData, prefix: "image"),
            width: bitmap.pixelsWide,
            height: bitmap.pixelsHigh
        )
    }
}

@MainActor
final class ClipboardPanelController {
    static let shared = ClipboardPanelController()

    private var windowController: NSWindowController?

    private init() {}

    func toggle() {
        if windowController?.window?.isVisible == true {
            windowController?.window?.orderOut(nil)
        } else {
            show()
        }
    }

    func show() {
        if windowController == nil {
            let window = NSPanel(
                contentRect: NSRect(x: 0, y: 0, width: 430, height: 580),
                styleMask: [.titled, .closable, .fullSizeContentView],
                backing: .buffered,
                defer: false
            )
            window.title = "Clipboard"
            window.titleVisibility = .hidden
            window.titlebarAppearsTransparent = true
            window.isMovableByWindowBackground = true
            window.level = .floating
            window.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
            window.contentView = NSHostingView(rootView: ClipboardHistoryPanelView())
            windowController = NSWindowController(window: window)
        }

        if let screen = NSScreen.main, let window = windowController?.window {
            let frame = screen.visibleFrame
            window.setFrameOrigin(NSPoint(x: frame.midX - window.frame.width / 2, y: frame.maxY - window.frame.height - 18))
        }

        NSApp.activate(ignoringOtherApps: true)
        windowController?.window?.makeKeyAndOrderFront(nil)
        windowController?.window?.orderFrontRegardless()
    }
}
