//
//  ClipboardMonitor.swift
//  boringNotch
//

import AppKit
import Combine
import CryptoKit
import Defaults
import Foundation
import UniformTypeIdentifiers

/// Watches `NSPasteboard.general` and records what the user copies.
///
/// There is no change-notification API for the general pasteboard, so polling `changeCount` is
/// the only option. Structurally this mirrors `DragDetector`, which already does change-count
/// tracking against the *drag* pasteboard.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    /// The de-facto standard interval among clipboard managers. A tick is one cheap IPC read of
    /// an integer; faster buys nothing, slower starts dropping rapid copy-copy-paste sequences.
    private static let pollInterval: TimeInterval = 0.5

    /// Pasteboard markers meaning "do not record me". Concealed is gated on a user setting;
    /// the rest are an explicit contract from the writing app and are always honoured.
    private static let alwaysIgnoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]
    private static let concealedType = "org.nspasteboard.ConcealedType"

    /// Courtesy marker so other clipboard managers can attribute our writes.
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private var enabledCancellable: AnyCancellable?

    private init() {
        enabledCancellable = Defaults.publisher(.clipboardHistoryEnabled)
            .sink { [weak self] change in
                Task { @MainActor in
                    if change.newValue {
                        self?.start()
                    } else {
                        self?.stop()
                    }
                }
            }
    }

    // MARK: - Lifecycle

    func startIfEnabled() {
        guard Defaults[.clipboardHistoryEnabled] else { return }
        start()
    }

    private func start() {
        stop()

        // Adopt the current clipboard rather than capturing it. Seeding from -1 would re-add
        // whatever is already on the board on every launch, producing a duplicate each time.
        lastChangeCount = NSPasteboard.general.changeCount

        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.tick() }
        }
        // .common so the timer keeps firing during menu and scroll tracking — precisely when
        // someone copies from a context menu. Tolerance lets the kernel coalesce wakeups.
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Writing

    /// The single place the app is allowed to write to the general pasteboard. Updating
    /// `lastChangeCount` here is what stops our own writes coming back as new captures.
    func performOwnWrite(_ body: (NSPasteboard) -> Void) {
        let pb = NSPasteboard.general
        pb.clearContents()
        body(pb)
        pb.setString(Bundle.main.bundleIdentifier ?? "", forType: Self.sourceType)
        // Sampled after every write: clearContents() bumps the counter, and so do some setData paths.
        lastChangeCount = pb.changeCount
    }

    // MARK: - Polling

    private func tick() {
        let pb = NSPasteboard.general
        let changeCount = pb.changeCount
        guard changeCount != lastChangeCount else { return }

        // Claim the change first. Every early return below must leave the counter advanced,
        // or a skipped payload is re-evaluated every 500ms forever.
        lastChangeCount = changeCount

        let typeIdentifiers = Set((pb.types ?? []).map(\.rawValue))
        guard !typeIdentifiers.contains(where: Self.alwaysIgnoredTypes.contains) else { return }
        if Defaults[.clipboardIgnoreConcealed], typeIdentifiers.contains(Self.concealedType) {
            return
        }

        let sourceBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        capture(from: pb, sourceBundleID: sourceBundleID)
    }

    /// Capture priority: files, then images, then links, then text.
    ///
    /// Order matters. A Finder copy of an image carries both a file URL and image data, and the
    /// file reference is strictly more useful; a browser copy carries HTML alongside a PNG, and
    /// the image is the better artifact. Each branch returns rather than falling through, so a
    /// disabled type never degrades into a surprise capture of a lower-priority representation.
    private func capture(from pb: NSPasteboard, sourceBundleID: String?) {
        if let urls = pb.readObjects(
            forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            guard Defaults[.clipboardCaptureFiles] else { return }
            captureFiles(urls, sourceBundleID: sourceBundleID)
            return
        }

        if let (imageData, uti) = readImage(from: pb) {
            guard Defaults[.clipboardCaptureImages] else { return }
            captureImage(imageData, uti: uti, sourceBundleID: sourceBundleID)
            return
        }

        guard let string = pb.string(forType: .string) else { return }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        if let url = webURL(from: trimmed) {
            guard Defaults[.clipboardCaptureLinks] else { return }
            insert(kind: .link(url), hashing: Data(url.absoluteString.utf8), sourceBundleID: sourceBundleID)
            return
        }

        guard Defaults[.clipboardCaptureText] else { return }
        insert(kind: .text(string), hashing: Data(string.utf8), sourceBundleID: sourceBundleID)
    }

    private func readImage(from pb: NSPasteboard) -> (Data, String)? {
        if let png = pb.data(forType: .png) { return (png, UTType.png.identifier) }
        if let tiff = pb.data(forType: .tiff) { return (tiff, UTType.tiff.identifier) }
        return nil
    }

    private func webURL(from string: String) -> URL? {
        guard !string.contains(where: \.isWhitespace),
              let url = URL(string: string),
              let scheme = url.scheme?.lowercased(),
              scheme == "http" || scheme == "https",
              url.host != nil else { return nil }
        return url
    }

    // MARK: - Kind-specific capture

    private func captureFiles(_ urls: [URL], sourceBundleID: String?) {
        // Mint bookmarks in this same run-loop tick, while the pasteboard's implicit sandbox
        // extension is still live. Failure is expected for some sources and is not fatal: the
        // path alone still supports re-copy, reveal and icon lookup.
        let refs = urls.map { url -> ClipboardFileRef in
            let bookmark = try? Bookmark(url: url)
            return ClipboardFileRef(
                bookmark: bookmark?.data,
                path: url.path,
                name: url.lastPathComponent
            )
        }

        let hashInput = Data(refs.map(\.path).sorted().joined(separator: "|").utf8)
        insert(kind: .files(refs), hashing: hashInput, sourceBundleID: sourceBundleID)
    }

    private func captureImage(_ data: Data, uti: String, sourceBundleID: String?) {
        let hash = Self.hash(data)

        // Already have this exact image: reuse the stored blob and just bump the existing entry,
        // rather than writing a file only to delete it again during dedup.
        if let existing = ClipboardStore.shared.items.first(where: { $0.contentHash == hash }) {
            ClipboardStore.shared.insert(
                ClipboardItem(kind: existing.kind, contentHash: hash, sourceBundleID: sourceBundleID))
            return
        }

        // Blob writing and thumbnail rendering are the expensive part; keep them off main.
        Task.detached(priority: .utility) {
            guard let ref = ClipboardBlobStore.shared.write(imageData: data, uti: uti) else { return }
            let item = ClipboardItem(
                kind: .image(blob: ref), contentHash: hash, sourceBundleID: sourceBundleID)
            await MainActor.run {
                ClipboardStore.shared.insert(item)
            }
        }
    }

    private func insert(kind: ClipboardItemKind, hashing data: Data, sourceBundleID: String?) {
        ClipboardStore.shared.insert(
            ClipboardItem(kind: kind, contentHash: Self.hash(data), sourceBundleID: sourceBundleID))
    }

    private static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
