//
//  ClipboardMonitorService.swift
//  boringNotch
//
//  Created by Claude on 2026-07-05.
//

import AppKit
import Defaults
import Foundation

/// Polls the general pasteboard for changes (macOS provides no pasteboard
/// change notification) and forwards new content to the history view model.
@MainActor
final class ClipboardMonitorService {
    static let shared = ClipboardMonitorService()

    /// Types written by password managers / transient sources that must never
    /// be recorded. See http://nspasteboard.org
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    /// Set right before this app writes to the pasteboard itself, so the
    /// monitor doesn't re-record our own copies.
    var ignoredChangeCount: Int = -1

    private init() {}

    var isMonitoring: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.8, repeats: true) { _ in
            Task { @MainActor in
                ClipboardMonitorService.shared.poll()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        guard changeCount != ignoredChangeCount else { return }

        if Defaults[.clipboardIgnoreConcealed] {
            let types = pasteboard.types ?? []
            if Self.concealedTypes.contains(where: types.contains) { return }
        }

        guard let item = extractItem(from: pasteboard) else { return }
        ClipboardHistoryViewModel.shared.add(item)
    }

    private func extractItem(from pasteboard: NSPasteboard) -> ClipboardItem? {
        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        // File URLs first: file copies also carry string representations.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return ClipboardItem(
                kind: .fileURL,
                fileURLStrings: urls.map(\.absoluteString),
                sourceAppBundleID: sourceApp
            )
        }

        // Images (e.g. screenshots copied to clipboard).
        if Defaults[.clipboardStoreImages],
           let image = NSImage(pasteboard: pasteboard),
           image.isValid
        {
            if let fileName = ClipboardPersistenceService.shared.storeImage(image) {
                return ClipboardItem(
                    kind: .image,
                    imageFileName: fileName,
                    sourceAppBundleID: sourceApp
                )
            }
            return nil
        }

        // Plain text / links.
        if let text = pasteboard.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            let isLink = trimmed.range(of: #"^https?://\S+$"#, options: .regularExpression) != nil
            return ClipboardItem(
                kind: isLink ? .link : .text,
                plainText: text,
                sourceAppBundleID: sourceApp
            )
        }

        return nil
    }
}
