//
//  ClipboardHistoryManager.swift
//  boringNotch
//
//  SPDX-License-Identifier: GPL-3.0-only
//

import AppKit
import Combine
import ImageIO

@MainActor
final class ClipboardHistoryManager: ObservableObject {
    static let shared = ClipboardHistoryManager(pasteboard: .general)

    @Published private(set) var items: [ClipboardHistoryItem] = []
    @Published private(set) var isPaused = false
    @Published private(set) var isMonitoring = false

    private let pasteboard: NSPasteboard
    private let sourceProvider: () -> ClipboardSourceApplication
    private let maximumItems: Int
    private let maximumTotalBytes: Int
    private let maximumItemBytes: Int
    private var lastChangeCount: Int
    private var timer: Timer?

    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let generatedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.SensitiveType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "com.apple.passwordmanager"
    ]
    private static let excludedBundlePrefixes = [
        "com.1password.", "com.agilebits.", "com.bitwarden.", "com.lastpass.",
        "com.dashlane.", "com.keepersecurity.", "com.keepassxc.", "org.keepassxc.",
        "com.strongbox.", "com.markmcguill.", "com.apple.passwords", "proton.pass",
        "me.proton.pass", "com.proton.pass", "com.callpod.keeper", "in.sinew.enpass"
    ]

    // Injectable pasteboards keep tests safely away from the user's current copy.
    init(
        pasteboard: NSPasteboard,
        maximumItems: Int = 100,
        maximumTotalBytes: Int = 20 * 1024 * 1024,
        maximumItemBytes: Int = 4 * 1024 * 1024,
        sourceProvider: @escaping () -> ClipboardSourceApplication = {
            let app = NSWorkspace.shared.frontmostApplication
            return ClipboardSourceApplication(name: app?.localizedName ?? "Unknown app", bundleIdentifier: app?.bundleIdentifier)
        }
    ) {
        self.pasteboard = pasteboard
        self.maximumItems = max(1, maximumItems)
        self.maximumTotalBytes = max(1, maximumTotalBytes)
        self.maximumItemBytes = max(1, maximumItemBytes)
        self.sourceProvider = sourceProvider
        self.lastChangeCount = pasteboard.changeCount
    }

    func startMonitoring() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.capturePasteboardChanges() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        isMonitoring = true
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
        isMonitoring = false
    }

    func setPaused(_ paused: Bool) {
        lastChangeCount = pasteboard.changeCount
        isPaused = paused
    }

    /// Evaluated only when hover opens the notch; detection timestamps need no extra polling.
    func hasRecentCopies(at now: Date = Date()) -> Bool {
        guard isMonitoring, !isPaused, items.count >= 2 else { return false }
        return items.prefix(2).allSatisfy { (0...30).contains(now.timeIntervalSince($0.capturedAt)) }
    }

    func clearHistory() {
        items.removeAll()
        lastChangeCount = pasteboard.changeCount
    }

    func delete(_ item: ClipboardHistoryItem) {
        items.removeAll { $0.id == item.id }
    }

    @discardableResult
    func copy(_ item: ClipboardHistoryItem) -> Bool {
        let output = NSPasteboardItem()
        switch item.content {
        case .text(let value, let isURL):
            output.setString(value, forType: .string)
            if isURL { output.setString(value, forType: .URL) }
        case .image(let data, let type, _):
            output.setData(data, forType: type)
        }
        // A copied history entry should not become its own enthusiastic new entry.
        output.setData(Data(), forType: Self.generatedType)
        pasteboard.clearContents()
        return pasteboard.writeObjects([output])
    }

    func capturePasteboardChanges() {
        let observedCount = pasteboard.changeCount
        guard observedCount != lastChangeCount else { return }
        guard !isPaused else {
            lastChangeCount = observedCount
            return
        }

        let types = pasteboard.types ?? []
        let source = sourceProvider()
        let declaredSource = pasteboard.string(forType: Self.sourceType)
        let isExcluded = types.contains { Self.excludedTypes.contains($0.rawValue) }
            || Self.isExcludedApplication(source.bundleIdentifier)
            || Self.isExcludedApplication(declaredSource)
        let content = isExcluded ? nil : readContent(types: types)

        // Another app can replace the pasteboard while a promised payload is being read.
        guard pasteboard.changeCount == observedCount else { return }
        lastChangeCount = observedCount
        guard let content else { return }

        let fingerprint = content.fingerprint
        let existingID = items.first { $0.fingerprint == fingerprint }?.id
        items.removeAll { $0.fingerprint == fingerprint }
        let item = ClipboardHistoryItem(id: existingID ?? UUID(), content: content, source: source)
        guard item.byteCount <= maximumTotalBytes else { return }
        items.insert(item, at: 0)
        var totalBytes = items.reduce(0) { $0 + $1.byteCount }
        while items.count > maximumItems || totalBytes > maximumTotalBytes {
            totalBytes -= items.removeLast().byteCount
        }
    }

    private static func isExcludedApplication(_ identifier: String?) -> Bool {
        guard let identifier = identifier?.lowercased() else { return false }
        return excludedBundlePrefixes.contains { identifier.hasPrefix($0) }
    }

    private func readContent(types: [NSPasteboard.PasteboardType]) -> ClipboardHistoryItem.Content? {
        for type in [NSPasteboard.PasteboardType.png, .tiff] where types.contains(type) {
            guard let data = pasteboard.data(forType: type), data.count <= maximumItemBytes,
                  let source = CGImageSourceCreateWithData(data as CFData, nil),
                  let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
                  let width = properties[kCGImagePropertyPixelWidth] as? Int,
                  let height = properties[kCGImagePropertyPixelHeight] as? Int,
                  width > 0, height > 0, Double(width) * Double(height) <= 40_000_000,
                  let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, [
                    kCGImageSourceCreateThumbnailFromImageAlways: true,
                    // Keep Retina tiles sharp while bounding retained pixels and never enlarging tiny copies.
                    kCGImageSourceThumbnailMaxPixelSize: min(320, max(width, height)),
                    kCGImageSourceCreateThumbnailWithTransform: true
                  ] as CFDictionary) else { continue }
            return .image(data, type: type, thumbnail: NSImage(cgImage: thumbnail, size: .zero))
        }

        for type in [NSPasteboard.PasteboardType.string, .URL] where types.contains(type) {
            guard let data = pasteboard.data(forType: type), data.count <= min(maximumItemBytes, 256 * 1024),
                  let value = pasteboard.string(forType: type),
                  !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { continue }
            let isURL = type == .URL || (URL(string: value)?.scheme.map { ["http", "https", "mailto"].contains($0.lowercased()) } ?? false)
            return .text(value, isURL: isURL)
        }
        return nil
    }
}
