name: Crowdin Sync

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Crowdin action
        uses: crowdin/github-action@8818ff65bfc4322384f983ea37e3926948c11745 #v2.15.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          create_pull_request: true
          pull_request_base_branch_name: dev
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
